---
- name: Install MicroK8s on all nodes
  hosts: master:workers
  become: true
  vars:
    microk8s_snap_channel: "1.34/stable"
    microk8s_bin: /snap/bin/microk8s
    snap_bin_path: /snap/bin
    kubelet_args_file: /var/snap/microk8s/current/args/kubelet
    kubelet_node_ip: "{{ hostvars[inventory_hostname].node_ip | default(ansible_host) }}"
  tasks:
    - name: Update apt cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Ensure snapd is installed
      ansible.builtin.apt:
        name: snapd
        state: present
      when: ansible_os_family == "Debian"

    - name: Install MicroK8s snap
      ansible.builtin.command: "snap install microk8s --classic --channel={{ microk8s_snap_channel }}"
      args:
        creates: "{{ microk8s_bin }}"

    - name: Add {{ ansible_user }} to the microk8s group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: microk8s
        append: true

    - name: Ensure kube config directory exists for {{ ansible_user }}
      ansible.builtin.file:
        path: "{{ ansible_user_dir | default('/home/' + ansible_user) }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0750"

    - name: Verify microk8s binary is present
      ansible.builtin.stat:
        path: "{{ microk8s_bin }}"
      register: microk8s_bin_stat

    - name: Fail if microk8s binary was not installed
      ansible.builtin.fail:
        msg: "MicroK8s binary not found at {{ microk8s_bin }} after installation."
      when: not microk8s_bin_stat.stat.exists

    - name: Pin kubelet node IP
      ansible.builtin.lineinfile:
        path: "{{ kubelet_args_file }}"
        regexp: '^--node-ip='
        line: "--node-ip={{ kubelet_node_ip }}"
        state: present
        create: yes
        backrefs: false
      notify: Restart microk8s

    - name: Force kubelet to use /etc/resolv.conf
      ansible.builtin.lineinfile:
        path: "{{ kubelet_args_file }}"
        regexp: '^--resolv-conf='
        line: "--resolv-conf=/etc/resolv.conf"
        state: present
        create: yes
        backrefs: false
      notify: Restart microk8s

    - name: Apply pending restarts before readiness checks
      ansible.builtin.meta: flush_handlers

    - name: Wait for MicroK8s to become ready
      ansible.builtin.command: "{{ microk8s_bin }} status --wait-ready"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ snap_bin_path }}"
      changed_when: false

  handlers:
    - name: Restart microk8s
      ansible.builtin.command: snap restart microk8s
      changed_when: true

- name: Configure master, generate token
  hosts: master
  become: true
  vars:
    microk8s_bin: /snap/bin/microk8s
    snap_bin_path: /snap/bin
  tasks:
    - name: Ensure MicroK8s is ready on master
      ansible.builtin.command: "{{ microk8s_bin }} status --wait-ready"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ snap_bin_path }}"
      changed_when: false

    - name: Enable DNS addon (safe to re-run)
      ansible.builtin.command: "{{ microk8s_bin }} enable dns"
      register: dns_enable
      changed_when: "'Nothing to do for addon dns' not in dns_enable.stdout"

    - name: Enable built-in image registry (safe to re-run)
      ansible.builtin.command: "{{ microk8s_bin }} enable registry"
      register: registry_enable
      changed_when: "'Nothing to do for addon registry' not in registry_enable.stdout"

    - name: Generate join token for workers
      ansible.builtin.command: "{{ microk8s_bin }} add-node --token-ttl 3600"
      register: add_node_raw
      changed_when: true

    - name: Extract worker join command
      ansible.builtin.set_fact:
        microk8s_join_command: >-
          {{
            (
              add_node_raw.stdout_lines
              | select('search', 'microk8s join')
              | select('search', '--worker')
              | list
              | first
            )
            | default(
              (add_node_raw.stdout_lines | select('search', 'microk8s join') | list | first),
              true
            )
            | trim
          }}

    - name: Rewrite join command to use absolute microk8s path
      ansible.builtin.set_fact:
        microk8s_join_command_bin: "{{ microk8s_join_command | regex_replace('^microk8s', microk8s_bin) }}"

    - name: Fail if join command was not found
      ansible.builtin.fail:
        msg: "Could not parse a microk8s join command from add-node output."
      when: microk8s_join_command is not defined or microk8s_join_command == ""

    - name: Show join command in log
      ansible.builtin.debug:
        var: microk8s_join_command_bin

- name: Join workers to the cluster
  hosts: workers
  become: true
  vars:
    join_command: "{{ hostvars[groups['master'][0]].microk8s_join_command_bin | default('') }}"
    microk8s_bin: /snap/bin/microk8s
    snap_bin_path: /snap/bin
  tasks:
    - name: Wait for MicroK8s to become ready on worker
      ansible.builtin.command: "{{ microk8s_bin }} status --wait-ready"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ snap_bin_path }}"
      changed_when: false

    - name: Ensure join command is available
      ansible.builtin.assert:
        that:
          - join_command != ""
        fail_msg: "Master did not publish a join command."

    - name: Join worker to the master
      ansible.builtin.command: "{{ join_command }}"
      register: join_result
      changed_when: "'already part of the cluster' not in join_result.stdout"

- name: Enforce kubelet network settings post-join (workers)
  hosts: workers
  become: true
  vars:
    microk8s_bin: /snap/bin/microk8s
    snap_bin_path: /snap/bin
    kubelet_args_file: /var/snap/microk8s/current/args/kubelet
    kubelet_node_ip: "{{ hostvars[inventory_hostname].node_ip | default(ansible_host) }}"
  tasks:
    - name: Pin kubelet node IP
      ansible.builtin.lineinfile:
        path: "{{ kubelet_args_file }}"
        regexp: '^--node-ip='
        line: "--node-ip={{ kubelet_node_ip }}"
        state: present
        create: yes
      notify: Restart microk8s service

    - name: Force kubelet to use /etc/resolv.conf
      ansible.builtin.lineinfile:
        path: "{{ kubelet_args_file }}"
        regexp: '^--resolv-conf='
        line: "--resolv-conf=/etc/resolv.conf"
        state: present
        create: yes
      notify: Restart microk8s service

    - name: Apply pending restarts
      ansible.builtin.meta: flush_handlers

    - name: Wait for MicroK8s to become ready after restart
      ansible.builtin.command: "{{ microk8s_bin }} status --wait-ready"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ snap_bin_path }}"
      changed_when: false

  handlers:
    - name: Restart microk8s service
      ansible.builtin.command: snap restart microk8s
      changed_when: true

- name: Configure cluster CNI autodetection
  hosts: master
  become: true
  vars:
    microk8s_bin: /snap/bin/microk8s
    snap_bin_path: /snap/bin
    calico_autodetect_cidr: 192.168.1.0/24
  tasks:
    - name: Ensure MicroK8s is ready on master
      ansible.builtin.command: "{{ microk8s_bin }} status --wait-ready"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ snap_bin_path }}"
      changed_when: false

    - name: Set Calico IP autodetection to site LAN
      ansible.builtin.command: >-
        {{ microk8s_bin }} kubectl -n kube-system set env daemonset/calico-node
        IP_AUTODETECTION_METHOD=cidr={{ calico_autodetect_cidr }}
      register: calico_env
      changed_when: "'configured' in calico_env.stdout or 'set' in calico_env.stdout"

- name: Deploy application stack to workers
  hosts: master
  become: true
  vars:
    microk8s_bin: /snap/bin/microk8s
    snap_bin_path: /snap/bin
    app_namespace: ipynb-stack
    worker_label_key: microk8s_app_role
    worker_label_value: worker
    manifest_src: k8s/microk8s-stack.yaml
    manifest_dest: /tmp/microk8s-stack.yaml
  tasks:
    - name: Ensure MicroK8s is ready on master
      ansible.builtin.command: "{{ microk8s_bin }} status --wait-ready"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ snap_bin_path }}"
      changed_when: false

    - name: Label worker nodes for app scheduling
      ansible.builtin.command: >-
        {{ microk8s_bin }} kubectl label node {{ item_node_name }}
        {{ worker_label_key }}={{ worker_label_value }} --overwrite
      loop: "{{ groups['workers'] }}"
      loop_control:
        loop_var: item_host
      vars:
        item_node_name: "{{ hostvars[item_host].node_name | default(hostvars[item_host].ansible_hostname | default(item_host)) }}"

    - name: Copy stack manifest to master
      ansible.builtin.copy:
        src: "{{ manifest_src }}"
        dest: "{{ manifest_dest }}"
        mode: "0644"

    - name: Apply stack manifest
      ansible.builtin.command: "{{ microk8s_bin }} kubectl apply -f {{ manifest_dest }}"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ snap_bin_path }}"
